services:
  # Zabbix MySQL Database
  zabbix-db:
    image: mysql:latest
    container_name: zabbix-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - ./zabbix_db:/var/lib/mysql
    networks:
      - zabbix-net

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    depends_on:
      - zabbix-db
    volumes:
      - ./zabbix_server:/var/lib/zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/London # Adjust timezone if needed
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  # Zabbix Agent (optional for local monitoring)
  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    volumes:
      - ./zabbix_agent:/var/lib/zabbix

  # phpMyAdmin for managing the MySQL database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: zabbix-db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - zabbix-db
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge
